
package de.fhdo.fhapp.timetable;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TimeTableBeanService", targetNamespace = "http://timetable.fhapp.fhdo.de/", wsdlLocation = "file:/C:/ws/timetable.wsdl")
public class TimeTableBeanService
    extends Service
{

    private final static URL TIMETABLEBEANSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(de.fhdo.fhapp.timetable.TimeTableBeanService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.fhdo.fhapp.timetable.TimeTableBeanService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/ws/timetable.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/ws/timetable.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TIMETABLEBEANSERVICE_WSDL_LOCATION = url;
    }

    public TimeTableBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimeTableBeanService() {
        super(TIMETABLEBEANSERVICE_WSDL_LOCATION, new QName("http://timetable.fhapp.fhdo.de/", "TimeTableBeanService"));
    }

    /**
     * 
     * @return
     *     returns TimeTableBean
     */
    @WebEndpoint(name = "TimeTableBeanPort")
    public TimeTableBean getTimeTableBeanPort() {
        return super.getPort(new QName("http://timetable.fhapp.fhdo.de/", "TimeTableBeanPort"), TimeTableBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeTableBean
     */
    @WebEndpoint(name = "TimeTableBeanPort")
    public TimeTableBean getTimeTableBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://timetable.fhapp.fhdo.de/", "TimeTableBeanPort"), TimeTableBean.class, features);
    }

}
