
package de.fhdo.fhapp.timetable;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TimeTableBean", targetNamespace = "http://timetable.fhapp.fhdo.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeTableBean {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "initialize", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.Initialize")
    @ResponseWrapper(localName = "initializeResponse", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.InitializeResponse")
    public void initialize();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentBranches", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.GetCurrentBranches")
    @ResponseWrapper(localName = "getCurrentBranchesResponse", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.GetCurrentBranchesResponse")
    public String getCurrentBranches();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActivitiesByDay", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.GetActivitiesByDay")
    @ResponseWrapper(localName = "getActivitiesByDayResponse", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.GetActivitiesByDayResponse")
    public String getActivitiesByDay(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActivitiesForWeek", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.GetActivitiesForWeek")
    @ResponseWrapper(localName = "getActivitiesForWeekResponse", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.GetActivitiesForWeekResponse")
    public String getActivitiesForWeek(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStaffList", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.GetStaffList")
    @ResponseWrapper(localName = "getStaffListResponse", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.GetStaffListResponse")
    public String getStaffList();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStaffByAbbreviation", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.GetStaffByAbbreviation")
    @ResponseWrapper(localName = "getStaffByAbbreviationResponse", targetNamespace = "http://timetable.fhapp.fhdo.de/", className = "de.fhdo.fhapp.timetable.GetStaffByAbbreviationResponse")
    public String getStaffByAbbreviation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
